### ISSUE TITLE
How to get this building?

### ISSUE THREAD

**Issue by locallycompact** [ShinKage/idris2-sdl#1]
Hi. Thanks for putting this up. I'm wondering what has happened that causes this to not build anymore.

Running against idris 0.3.0, there's two easy to fix exhaustiveness checks in `SDL/Elab.idr`, but then I run into a lot of linearity issues trying to build the example.

```
snoc : (1 _ : Vect len a) -> (1 _ : a) -> Vect (S len) a
snoc [] x = [x]
snoc (y :: xs) x = y :: snoc xs x
```

I'm presuming this did build at some point. Presumably this is due to different Vect definition? As I can't see what else is wrong.

**Comment by glomurno** [comment]
There were some major changes related to quantities from 0.2.0 to 0.3.0. Unfortunately I did not have much time to check if the example was still working, I'll take a look now. Thanks for the heads up.

**Comment by glomurno** [comment]
@locallycompact, as I suspected, the removal of linearity subtyping (https://github.com/idris-lang/Idris2/pull/879) was causing issues with the example, however the version without linear annotations works fine, so I've reverted back to it (Note that the library itself still uses linearity to enforce the correct usage of the SDL bindings, the change is only relevant for the example).
Mind that I've tested the code only on Mac, however it should work well also on the other supported platforms.
I've also updated the READMEs to show how to build the library and the example.

**Comment by locallycompact** [comment]
Thanks, I'm using some random semi-recent mainline version on NixOS so I'm running into this:

```
[nix-shell:~/idris2-sdl]$ make
idris2 --build sdl.ipkg
make[1]: Entering directory '/home/lc/idris2-sdl/sdl_glue'
make[1]: 'libidrissdl.so' is up to date.
make[1]: Leaving directory '/home/lc/idris2-sdl/sdl_glue'
1/5: Building SDL.Elab (src/SDL/Elab.idr)
Error: While processing right hand side of mkTy. When unifying FC and Name.
Mismatch between: FC and Name.

src/SDL/Elab.idr:40:21--40:28
    |
 40 | mkTy = MkTy EmptyFC EmptyFC
```

Not sure what I do about that, looks like it changed here:

https://github.com/idris-lang/Idris2/commit/7f495999bd18b970da6a070ac0e76fb5c58dd7fd#diff-5ad905466a2536472490b14bde7ba699f63c1b890e5c059af9438067dbff8780R109


Also get some tiny issue with:

```
2/3: Building GameOfLife (GameOfLife.idr)
Error: While processing right hand side of randomGame. While processing right hand side of randomGame,randomZipper. Undefined
name n. 

GameOfLife.idr:176:69--176:70
     |
 176 |       before <- traverse (const $ fromInt <$> randomIO) $ replicate n ()
```

This seems to go away by bringing n into scope like

```
-    randomZipper = do
+    randomZipper {n} = do
```

**Comment by locallycompact** [comment]
Actually I guess it's my version that's older.

**Comment by glomurno** [comment]
The code was tested using the latest master. I'm not sure what is the version you are running, but there were some progress related to nix packaging on the idris2 repository, maybe you can update that way, if you are running a prebundled version.

**Comment by locallycompact** [comment]
I have success. Game is running. Thank you very much for your help.
